package libxml_2_0

import (
	"github.com/goplus/llgo/c"
	_ "unsafe"
)

const UFOLDCASEDEFAULT c.Int = 0
const UFOLDCASEEXCLUDESPECIALI c.Int = 1
const UTITLECASEWHOLESTRING c.Int = 32
const UTITLECASESENTENCES c.Int = 64
const UTITLECASENOLOWERCASE c.Int = 256
const UTITLECASENOBREAKADJUSTMENT c.Int = 512
const UTITLECASEADJUSTTOCASED c.Int = 1024
const UEDITSNORESET c.Int = 8192
const UOMITUNCHANGEDTEXT c.Int = 16384
const UCOMPARECODEPOINTORDER c.Int = 32768
const UCOMPAREIGNORECASE c.Int = 65536
const UNORMINPUTISFCD c.Int = 131072
