package libxml_2_0

import (
	"github.com/goplus/llgo/c"
	_ "unsafe"
)

const UDEBUG c.Int = 0
const UCLNNOAUTOCLEANUP c.Int = 1
const UDISABLERENAMING c.Int = 0
const UNODEFAULTINCLUDEUTFHEADERS c.Int = 0
const UOVERRIDECXXALLOCATION c.Int = 1
const UENABLETRACING c.Int = 0
const UCONFIGENABLEPLUGINS c.Int = 0
const UENABLEDYLOAD c.Int = 1
const UCHECKDYLOAD c.Int = 1
const UDEFAULTSHOWDRAFT c.Int = 1
const ULIBSUFFIXCNAMESTRING string = ""
const UCONFIGONLYCOLLATION c.Int = 0
const UCONFIGNOFILEIO c.Int = 0
const UCONFIGNOCONVERSION c.Int = 0
const UCONFIGONLYHTMLCONVERSION c.Int = 0
const UCONFIGNOLEGACYCONVERSION c.Int = 0
const UCONFIGNONORMALIZATION c.Int = 0
const UCONFIGUSEMLPHRASEBREAKING c.Int = 0
const UCONFIGNOBREAKITERATION c.Int = 0
const UCONFIGNOIDNA c.Int = 0
const UCONFIGUSEWINDOWSLCIDMAPPINGAPI c.Int = 1
const UCONFIGNOCOLLATION c.Int = 0
const UCONFIGNOFORMATTING c.Int = 0
const UCONFIGNOMF2 c.Int = 0
const UCONFIGNOTRANSLITERATION c.Int = 0
const UCONFIGNOREGULAREXPRESSIONS c.Int = 0
const UCONFIGNOSERVICE c.Int = 0
const UCONFIGHAVEPARSEALLINPUT c.Int = 1
const UCONFIGNOFILTEREDBREAKITERATION c.Int = 0
