package libxml_2_0

import (
	"github.com/goplus/llgo/c"
	_ "unsafe"
)

const USHAPELENGTHGROWSHRINK c.Int = 0
const USHAPELAMALEFRESIZE c.Int = 0
const USHAPELENGTHFIXEDSPACESNEAR c.Int = 1
const USHAPELAMALEFNEAR c.Int = 1
const USHAPELENGTHFIXEDSPACESATEND c.Int = 2
const USHAPELAMALEFEND c.Int = 2
const USHAPELENGTHFIXEDSPACESATBEGINNING c.Int = 3
const USHAPELAMALEFBEGIN c.Int = 3
const USHAPELAMALEFAUTO c.Int = 65536
const USHAPELENGTHMASK c.Int = 65539
const USHAPELAMALEFMASK c.Int = 65539
const USHAPETEXTDIRECTIONLOGICAL c.Int = 0
const USHAPETEXTDIRECTIONVISUALRTL c.Int = 0
const USHAPETEXTDIRECTIONVISUALLTR c.Int = 4
const USHAPETEXTDIRECTIONMASK c.Int = 4
const USHAPELETTERSNOOP c.Int = 0
const USHAPELETTERSSHAPE c.Int = 8
const USHAPELETTERSUNSHAPE c.Int = 16
const USHAPELETTERSSHAPETASHKEELISOLATED c.Int = 24
const USHAPELETTERSMASK c.Int = 24
const USHAPEDIGITSNOOP c.Int = 0
const USHAPEDIGITSEN2AN c.Int = 32
const USHAPEDIGITSAN2EN c.Int = 64
const USHAPEDIGITSALEN2ANINITLR c.Int = 96
const USHAPEDIGITSALEN2ANINITAL c.Int = 128
const USHAPEDIGITSRESERVED c.Int = 160
const USHAPEDIGITSMASK c.Int = 224
const USHAPEDIGITTYPEAN c.Int = 0
const USHAPEDIGITTYPEANEXTENDED c.Int = 256
const USHAPEDIGITTYPERESERVED c.Int = 512
const USHAPEDIGITTYPEMASK c.Int = 768
const USHAPEAGGREGATETASHKEEL c.Int = 16384
const USHAPEAGGREGATETASHKEELNOOP c.Int = 0
const USHAPEAGGREGATETASHKEELMASK c.Int = 16384
const USHAPEPRESERVEPRESENTATION c.Int = 32768
const USHAPEPRESERVEPRESENTATIONNOOP c.Int = 0
const USHAPEPRESERVEPRESENTATIONMASK c.Int = 32768
const USHAPESEENTWOCELLNEAR c.Int = 2097152
const USHAPESEENMASK c.Int = 7340032
const USHAPEYEHHAMZATWOCELLNEAR c.Int = 16777216
const USHAPEYEHHAMZAMASK c.Int = 58720256
const USHAPETASHKEELBEGIN c.Int = 262144
const USHAPETASHKEELEND c.Int = 393216
const USHAPETASHKEELRESIZE c.Int = 524288
const USHAPETASHKEELREPLACEBYTATWEEL c.Int = 786432
const USHAPETASHKEELMASK c.Int = 917504
const USHAPESPACESRELATIVETOTEXTBEGINEND c.Int = 67108864
const USHAPESPACESRELATIVETOTEXTMASK c.Int = 67108864
const USHAPETAILNEWUNICODE c.Int = 134217728
const USHAPETAILTYPEMASK c.Int = 134217728
